# Generated by Django 3.2.5 on 2021-08-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('years', models.CharField(max_length=4, verbose_name='Год')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Да/Нет?')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='slug')),
                ('discription', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('video', models.FileField(blank=True, upload_to='movie/%Y/%m/%d/', verbose_name='Видео')),
                ('video_poster', models.ImageField(blank=True, upload_to='poster/%Y/%m/%d/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-years', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Film_to_rejicer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_app.film')),
            ],
            options={
                'verbose_name': 'Режиссёр фильма',
                'verbose_name_plural': 'Режисcёры фильма',
                'ordering': ['id_film'],
            },
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rejicer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=300, verbose_name='Имя')),
                ('birthday_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('fr', models.ManyToManyField(through='films_app.Film_to_rejicer', to='films_app.Film')),
            ],
            options={
                'verbose_name': 'Режисер',
                'verbose_name_plural': 'Режисеры',
                'ordering': ['fullName'],
            },
        ),
        migrations.AddField(
            model_name='film_to_rejicer',
            name='id_rejicer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_app.rejicer'),
        ),
        migrations.AddField(
            model_name='film',
            name='id_janr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_app.janr', verbose_name='Жанр'),
        ),
    ]
