# Generated by Django 3.2.5 on 2021-08-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0002_auto_20210805_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='actor/%Y/%m/%d/', verbose_name='Фото актёра'),
        ),
    ]
