# Generated by Django 3.2.5 on 2021-08-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0003_actor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday_place',
            field=models.CharField(max_length=100, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='actor',
            name='growth',
            field=models.CharField(max_length=100, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='actor/%Y/%m/%d/', verbose_name='Актёр'),
        ),
    ]
