# Generated by Django 3.2.5 on 2021-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0006_film_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/%Y/%m/%d/', verbose_name='Постер'),
        ),
    ]
